### ISSUE TITLE
Screen shakes on certain sizes

### ISSUE THREAD

**Issue by niriikon** [jiisloth/MK24scoreboard#3]
Screen starts shaking on 100% zoom and is fixed when first increasing zoom and then resuming. The issue also returns when decreasing zoom and then increasing it. The issue happens between zooms of 50% and 150%.

Specs:
- OS: Debian 9.2 Stretch 64bit
- Browser: Chromium 62.0.3202.89
- Screen size: 1366 x 768

**Comment by jiisloth** [comment]
Issue comes from scroll bar popping up and lowering screen size and then again disapearing. Might need to disable scroll

**Comment by jiisloth** [comment]
Fixed by disabling scrollbar
